### PR TITLE
fix permission issue and remove prometheus metrics

### LINKED ISSUE #1079: review rbac permissions with regards to k8s api changes
**What would you like to be added**:

Audit this.

- [x] remove permissions not needed (specifically jobs, cronjobs, statefulsets)

- [x] update groups for k8s 1.16

https://github.com/blackducksoftware/synopsys-operator/blob/5bbc3d6138c8a6a8567bf949cb4bed301c4b244b/pkg/soperator/soperator_resources.go#L337

**Why is this needed**:

### PR DESCRIPTION
**Pull request by msenmurugan**
fixes #1079

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1082#" title="Author self-approved">msenmurugan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/release-2019.11.x/OWNERS)~~ [msenmurugan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by operator-r2d2** [comment]
@msenmurugan: once the present PR merges, I will cherry-pick it on top of master in a new PR and assign it to you.

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/1082#issuecomment-554447984):

>/cherrypick master


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: pkg/soperator/soperator_components.go [hunk 1]
```diff
@@ -103,7 +103,6 @@ func (specConfig *SpecConfig) GetComponents() (*api.ComponentList, error) {
 	}
 	components := &api.ComponentList{
 		Deployments:     []*components.Deployment{deployment},
-		Services:        specConfig.getOperatorService(),
```
Comment (yashbhutwala) [inline pkg/soperator/soperator_components.go]: What is this for?

File: pkg/soperator/soperator_resources.go [hunk 2]
```diff
@@ -359,16 +283,10 @@ func (specConfig *SpecConfig) getOperatorClusterRole() *horizoncomponents.Cluste
...
-		Verbs:     []string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"},
-		APIGroups: []string{"batch", "extensions"},
-		Resources: []string{"jobs", "cronjobs"},
-	})
-
 	synopsysOperatorClusterRole.AddPolicyRule(horizonapi.PolicyRuleConfig{
 		Verbs:     []string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"},
 		APIGroups: []string{"extensions", "apps"},
-		Resources: []string{"deployments", "deployments/scale", "deployments/rollback", "statefulsets", "statefulsets/scale", "replicasets", "replicasets/scale", "daemonsets"},
+		Resources: []string{"deployments", "deployments/scale", "deployments/rollback"},
```
Comment (yashbhutwala) [inline pkg/soperator/soperator_resources.go]: Can you address TODO notes from here: https://github.com/blackducksoftware/synopsys-operator/pull/1080/files?  

If we're gonna clean up the RBAC, let's clean it all 😄

File: pkg/synopsysctl/cmd_migrate.go [hunk 3]
```diff
@@ -100,6 +103,13 @@ var migrateCmd = &cobra.Command{
 			return err
 		}
 
+		// Delete the prometheus metrics
+		prometheusCrdUpdater := crdupdater.NewCRUDComponents(restconfig, kubeClient, false, false, namespaceToMigrate, "", &api.ComponentList{}, "app=synopsys-operator,component=prometheus", false)
+		_, errs := prometheusCrdUpdater.CRUDComponents()
+		if errs != nil {
+			return fmt.Errorf("failed to delete Prometheus components: %+v", errs)
```
Comment (yashbhutwala) [inline pkg/synopsysctl/cmd_migrate.go]: I'd prefer to rather just fail silently and move on.  So, not being able to delete Prometheus is not a blocker

File: pkg/soperator/soperator_components.go (hunk 1 above)
Comment (msenmurugan) [reply pkg/soperator/soperator_components.go]: For prometheus metrics, we created this service previously. Since we are removing prometheus metrics, we don't need it.

Comment (yashbhutwala) [reply pkg/soperator/soperator_components.go]: This seems to have the operator service and the ui service tho

File: pkg/soperator/soperator_resources.go (hunk 2 above)
Comment (msenmurugan) [reply pkg/soperator/soperator_resources.go]: added TODO back.. But removed something which I knew

File: pkg/synopsysctl/cmd_migrate.go (hunk 3 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_migrate.go]: For sure, it won't create any errors until if you are having cluster issue. But I have updated the code to log the errors instead of return.

**Comment by msenmurugan** [comment]
tested against kube 1.9 and kube 1.15

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1082#" title="Author self-approved">msenmurugan</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1082#pullrequestreview-318306811" title="Approved">yashbhutwala</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/release-2019.11.x/OWNERS)~~ [msenmurugan,yashbhutwala]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by msenmurugan** [comment]
tested against kube 1.16 as well

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1082#" title="Author self-approved">msenmurugan</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/1082#issuecomment-555725482" title="LGTM">yashbhutwala</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/release-2019.11.x/OWNERS)~~ [msenmurugan,yashbhutwala]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by operator-r2d2** [comment]
@msenmurugan: new pull request created: #1090

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/1082#issuecomment-554447984):

>/cherrypick master


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
