### PR TITLE
bug fixes

### LINKED ISSUE #550: in cluster-scope operator, don't require providing namespace when updating black duck
If you install Synopsys Operator with cluster scope, and then install Black Duck in a namespace that differs from the Black Duck name, don't require the user to specify both the name and the namespace when running the "synopsysctl update blackduck" command.

Here's how to reproduce this problem:

1) Install Synopsys Operator with cluster scope
2) Install Black Duck where the name is different from the namespace.  For example:

sc create blackduck jb-bd --namespace jbbdns

3) Now, try to update the Black Duck instance without specifying the namespace, for example:

sc update blackduck jb-bd --expose-ui NODEPORT

The command above will fail with the message:
ERRO[0000] synopsyctl failed: unable to get jb-bd namespace due to namespaces "jb-bd" not found 

The problem here is that synopsysctl is assuming that in cluster scope, the Black Duck name and namespace will be the same, but that isn't always going to be the case.

### PR DESCRIPTION
**Pull request by msenmurugan**
* delete Black Duck not removing the labels from namespace
* destroy operator creating namespace
* removal of create namespace logic and use operator namespace
* update resources not finding the namespace automatically
* removed the incorrect alias for Black Duck native command
* OpsSight labels to be consistent with others

TODO: removal of namespace creation will be in separate PR

fixes #550

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/559#" title="Author self-approved">msenmurugan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [msenmurugan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by operator-r2d2** [comment]
@msenmurugan: once the present PR merges, I will cherry-pick it on top of release-2019.6.x in a new PR and assign it to you.

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/559#issuecomment-505724401):

>/cherrypick release-2019.6.x


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

File: pkg/synopsysctl/cmd_destroy.go [hunk 1]
```diff
@@ -89,28 +95,35 @@ func destroy(namespace string) error {
...
 
-	log.Infof("deleting the Synopsys Operator in namespace '%s'", namespace)
-	// delete Synopsys Operator instance
-	commonConfig := crdupdater.NewCRUDComponents(restconfig, kubeClient, false, false, namespace, &api.ComponentList{}, "app=synopsys-operator", false)
-	_, crudErrors := commonConfig.CRUDComponents()
-	if len(crudErrors) > 0 {
-		log.Errorf("unable to delete the Synopsys Operator in namespace '%s' due to %+v", namespace, err)
-	}
+		// delete Synopsys Operator instance
+		if isExist {
```
Comment (yashbhutwala) [inline pkg/synopsysctl/cmd_destroy.go]: Why this check again?  Doesn't `ifExist` already have to be true to even get inside this conditional (i.e.: line 102)?

Comment (yashbhutwala) [reply pkg/synopsysctl/cmd_destroy.go]: nm, i see it's reset in line 103, maybe control flow readability could be improved

File: pkg/crdupdater/namespace.go [hunk 2]
```diff
@@ -89,5 +108,24 @@ func (n *Namespace) remove() error {
...
+	namespace.Labels = util.InitLabels(namespace.Labels)
+	var app, name string
+	if appVal, ok := n.config.expectedLabels["app"]; ok {
+		app = appVal.value[0]
+	}
+	if nameVal, ok := n.config.expectedLabels["name"]; ok {
+		name = nameVal.value[0]
+	}
+	if val, ok := namespace.Labels[fmt.Sprintf("synopsys.com/%s.%s", app, name)]; !ok || val != n.config.version {
+		if len(app) > 0 && len(name) > 0 && len(n.config.version) > 0 {
```
Comment (rrati) [inline pkg/crdupdater/namespace.go]: If this case is false we probably should log an error with the values we wanted to use.  This failure seems like something that shouldn't happen, but if did we'd want to know the data it was trying to use

File: pkg/synopsysctl/cmd_destroy.go [hunk 3]
```diff
@@ -65,7 +66,11 @@ var destroyCmd = &cobra.Command{
 				}
 				if metav1.NamespaceAll != namespace {
 					operatorNamespace = namespace
+				} else {
+					log.Infof("destroy Synopsys Operator defaulting to namespace '%s'...", operatorNamespace)
```
Comment (rrati) [inline pkg/synopsysctl/cmd_destroy.go]: These else conditions aren't needed.  Just put a log before the destroy call saying "destroying Synopsys Operator in NS ..." or whatever.

File: pkg/synopsysctl/cmd_destroy.go [hunk 4]
```diff
@@ -52,6 +52,7 @@ var destroyCmd = &cobra.Command{
 		// Read Commandline Parameters
 		if len(args) > 0 {
 			for _, operatorNamespace := range args {
+				log.Infof("destroying Synopsys Operator in namespace '%s'...", operatorNamespace)
 				return destroy(operatorNamespace)
 			}
 		} else {
```
Comment (rrati) [inline pkg/synopsysctl/cmd_destroy.go]: We should only act if there is 1 operator in the system and it is cluster scoped.  Anything else is ambiguous to the user.

File: pkg/synopsysctl/cmd_destroy.go [hunk 5]
```diff
@@ -89,28 +95,35 @@ func destroy(namespace string) error {
...
-		return fmt.Errorf("%s. It is not recommended to destroy the Synopsys Operator so these resources can continue to be managed. If you are sure you want to delete the Synopsys Operator anyway then you can use the 'force' option which will keep all the instances and delete only the Synopsys Operator", err.Error())
-	}
+	if isExist {
+		isExist, err := util.CheckResourceNamespace(restconfig, kubeClient, strings.Join(crds, ","), namespace, true)
+		if isExist && err != nil && isForceDestroy {
+			log.Warnf("%s. namespace cannot be deleted", err.Error())
+		} else if isExist && err != nil && !isForceDestroy {
+			return fmt.Errorf("%s. It is not recommended to destroy the Synopsys Operator so these resources can continue to be managed. If you are sure you want to delete the Synopsys Operator anyway then you can use the 'force' option which will keep all the instances and delete only the Synopsys Operator", err.Error())
+		} else if err != nil {
+			log.Error(err)
```
Comment (rrati) [inline pkg/synopsysctl/cmd_destroy.go]: should return err

File: pkg/synopsysctl/cmd_destroy.go [hunk 6]
```diff
@@ -74,11 +79,12 @@ var destroyCmd = &cobra.Command{
...
 
 func destroy(namespace string) error {
-	log.Infof("destroying Synopsys Operator in namespace '%s'...", namespace)
 	crds := []string{}
+	var isExist bool
+	// get the synopsys operator configmap to get the crd names and cluster scope
 	cm, err := util.GetConfigMap(kubeClient, namespace, "synopsys-operator")
 	if err != nil {
-		log.Errorf("unable to find the 'synopsy-operator' config map in namespace '%s' due to %+v", namespace, err)
+		log.Errorf("error getting the config map in namespace '%s' due to %+v", namespace, err)
```
Comment (rrati) [inline pkg/synopsysctl/cmd_destroy.go]: return an error instead of logging

File: pkg/synopsysctl/cmd_destroy.go [hunk 7]
```diff
@@ -197,7 +210,9 @@ func destroy(namespace string) error {
 		}
 	}
 
-	log.Infof("successfully submitted destroy Synopsys Operator in namespace '%s'", namespace)
+	if isExist {
```
Comment (rrati) [inline pkg/synopsysctl/cmd_destroy.go]: This isn't a reliable state of the result of the action.  It's used and overwritten multiple times and since logs are printed instead of errors returned, this statement can be reached after errors are thrown.  Suggest re-working logic to return errors instead of printing logs, then print log if deletion is successful.  Probably better to to move this success message where the NS is actually deleted too.

File: pkg/synopsysctl/utils.go [hunk 8]
```diff
@@ -236,12 +236,13 @@ func getInstanceInfo(mock bool, name string, crdType string, crdName string, inp
 
 	// Check Number of Arguments
 	if crdScope != apiextensions.ClusterScoped && len(namespace) == 0 {
-		return "", "", "", fmt.Errorf("namespace to create an '%s' instance needs to be provided", inputNamespace)
+		return "", "", "", fmt.Errorf("namespace to create/update/delete an '%s' instance needs to be provided", inputNamespace)
```
Comment (rrati) [inline pkg/synopsysctl/utils.go]: namespace for instance '%s" needs to be provided.

File: pkg/util/common.go [hunk 9]
```diff
@@ -1644,37 +1643,39 @@ func CheckResourceNamespace(restConfig *rest.Config, kubeClient *kubernetes.Clie
...
+	return true, nil
 }
 
 // DeleteResourceNamespace deletes the namespace if none of the other resource types are running
-func DeleteResourceNamespace(restConfig *rest.Config, kubeClient *kubernetes.Clientset, crdNames string, namespace string, isOperator bool) error {
-	err := CheckResourceNamespace(restConfig, kubeClient, crdNames, namespace, isOperator)
-	if err == nil {
+func DeleteResourceNamespace(restConfig *rest.Config, kubeClient *kubernetes.Clientset, crdNames string, resourceName string, namespace string, name string, isOperator bool) []error {
+	isExist, err := CheckResourceNamespace(restConfig, kubeClient, crdNames, namespace, isOperator)
+	if isExist && err == nil {
```
[the remark this answers is not in the document]
Comment (msenmurugan) [reply pkg/util/common.go]: done

File: pkg/apps/alert/alert.go [hunk 10]
```diff
@@ -158,30 +157,23 @@ func (a *Alert) Delete(name string) error {
 			namespace = ns.Items[0].Name
 		} else {
 			log.Errorf("unable to find %s Alert instance namespace", name)
```
[the remark this answers is not in the document]
Comment (msenmurugan) [reply pkg/apps/alert/alert.go]: done

File: pkg/util/common.go [hunk 11]
```diff
@@ -1644,37 +1643,39 @@ func CheckResourceNamespace(restConfig *rest.Config, kubeClient *kubernetes.Clie
...
-
-	return nil
+	return true, nil
 }
 
 // DeleteResourceNamespace deletes the namespace if none of the other resource types are running
-func DeleteResourceNamespace(restConfig *rest.Config, kubeClient *kubernetes.Clientset, crdNames string, namespace string, isOperator bool) error {
-	err := CheckResourceNamespace(restConfig, kubeClient, crdNames, namespace, isOperator)
-	if err == nil {
+func DeleteResourceNamespace(restConfig *rest.Config, kubeClient *kubernetes.Clientset, crdNames string, resourceName string, namespace string, name string, isOperator bool) []error {
```
[the remark this answers is not in the document]
Comment (msenmurugan) [reply pkg/util/common.go]: done

File: pkg/synopsysctl/cmd_destroy.go (hunk 3 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: Just caution the user that we are defaulting to synopsys operator

File: pkg/synopsysctl/cmd_destroy.go (hunk 4 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: The customer can have 3 cluster scope operators with one resource enabled on each operator.

File: pkg/synopsysctl/cmd_destroy.go (hunk 5 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: just proceeding down to delete the cluster roles, role bindings

File: pkg/synopsysctl/cmd_destroy.go (hunk 6 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: done

File: pkg/synopsysctl/cmd_destroy.go (hunk 7 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: done

File: pkg/synopsysctl/utils.go (hunk 8 above)
Comment (msenmurugan) [reply pkg/synopsysctl/utils.go]: done

File: pkg/apps/alert/alert.go [hunk 12]
```diff
@@ -158,30 +157,23 @@ func (a *Alert) Delete(name string) error {
...
-	if a.config.IsClusterScoped {
-		err := util.DeleteResourceNamespace(a.kubeConfig, a.kubeClient, a.config.CrdNames, namespace, false)
-		if err != nil {
-			return errors.Annotatef(err, "unable to delete namespace %s", namespace)
-		}
-	}
-
-	// update the namespace label if the version of the app got deleted
-	if isNamespaceExist, err := util.CheckAndUpdateNamespace(a.kubeClient, util.AlertName, namespace, name, "", true); isNamespaceExist {
+	err := util.DeleteResourceNamespace(a.kubeConfig, a.kubeClient, a.config.CrdNames, util.AlertName, namespace, name, false)
```
[the remark this answers is not in the document]
Comment (msenmurugan) [reply pkg/apps/alert/alert.go]: done

File: pkg/crdupdater/namespace.go [hunk 13]
```diff
@@ -53,18 +57,33 @@ func (n *Namespace) buildNewAndOldObject() error {
...
+	ns, err := n.get(n.config.namespace)
 	if err != nil {
 		namespace := components.NewNamespace(
 			horizonapi.NamespaceConfig{
 				Name:      n.config.namespace,
 				Namespace: n.config.namespace,
 			})
-		namespace.AddLabels(map[string]string{"owner": "synopsys-operator"})
+		labels := make(map[string]string, 0)
+		labels["owner"] = "synopsys-operator"
```
[the remark this answers is not in the document]
Comment (msenmurugan) [reply pkg/crdupdater/namespace.go]: done

File: pkg/crdupdater/namespace.go (hunk 2 above)
Comment (msenmurugan) [reply pkg/crdupdater/namespace.go]: done

File: pkg/synopsysctl/cmd_destroy.go (hunk 4 above)
Comment (rrati) [reply pkg/synopsysctl/cmd_destroy.go]: True, but even more so why we shouldn't act if there isn't a namespace given. :) In the case where the user just does "synopsysctl destroy" we need to either error all the time unless a NS is given, or only act if there is 1 operator in the system.  There's no other way the user could know what to expect.

File: pkg/synopsysctl/cmd_destroy.go (hunk 3 above)
Comment (rrati) [reply pkg/synopsysctl/cmd_destroy.go]: We can accomplish that same information with a common log message before destroy.  Whether we default or not the user wouldn't be able to do anything with the fact that we are using defaults, so might as well simplify the code and just have a single log message denoting where we are destroying the operator.

File: pkg/synopsysctl/cmd_destroy.go [hunk 14]
```diff
@@ -74,51 +79,59 @@ var destroyCmd = &cobra.Command{
...
-		}
-		if crdNames, ok := cmData["CrdNames"]; ok {
-			crds = strings.Split(crdNames.(string), ",")
-		}
-	}
-
 	// delete namespace
-	checkErr := util.CheckResourceNamespace(restconfig, kubeClient, strings.Join(crds, ","), namespace, true)
-	if err != nil && isForceDestroy {
+	isNamespaceExist, err := util.CheckResourceNamespace(kubeClient, namespace, "", true)
```
Comment (rrati) [inline pkg/synopsysctl/cmd_destroy.go]: If isNamespaceExist{
<ns delete logic>
}

File: pkg/synopsysctl/cmd_destroy.go [hunk 15]
```diff
@@ -74,51 +79,59 @@ var destroyCmd = &cobra.Command{
...
+	if isNamespaceExist && err != nil && isForceDestroy {
```
Comment (rrati) [inline pkg/synopsysctl/cmd_destroy.go]: This can be simplified as:

if err != nil {
  if isForceDestory {
    log.Warnf("namespace '%s' cannot be deleted: %v", namespace, err)
  } else {
    return fmt.Errorf("%s. It is not recommended to destroy the Synopsys Operator so these resources can continue to be managed. If you are sure you want to delete the Synopsys Operator anyway then you can use the 'force' option which will keep all the instances and delete only the Synopsys Operator", err.Error())
  }
}

File: pkg/synopsysctl/cmd_destroy.go [hunk 16]
```diff
@@ -74,51 +79,59 @@ var destroyCmd = &cobra.Command{
...
 	}
 
-	log.Infof("deleting the Synopsys Operator in namespace '%s'", namespace)
 	// delete Synopsys Operator instance
-	commonConfig := crdupdater.NewCRUDComponents(restconfig, kubeClient, false, false, namespace, &api.ComponentList{}, "app=synopsys-operator", false)
-	_, crudErrors := commonConfig.CRUDComponents()
-	if len(crudErrors) > 0 {
-		log.Errorf("unable to delete the Synopsys Operator in namespace '%s' due to %+v", namespace, err)
-	}
+	if isNamespaceExist {
```
Comment (rrati) [inline pkg/synopsysctl/cmd_destroy.go]: If we're here, we know NS exists so need for this if block

File: pkg/synopsysctl/cmd_destroy.go [hunk 17]
```diff
@@ -74,51 +79,59 @@ var destroyCmd = &cobra.Command{
...
-			log.Errorf("unable to delete the Synopsys Operator namespace due to %+v", err)
+		log.Infof("deleting the Synopsys Operator resources in namespace '%s'", namespace)
+		if err == nil {
+			err = util.DeleteNamespace(kubeClient, namespace)
+			if err != nil {
+				log.Errorf("unable to delete the Synopsys Operator namespace due to %+v", err)
+			}
+		}
+
+		commonConfig := crdupdater.NewCRUDComponents(restconfig, kubeClient, false, false, namespace, "", &api.ComponentList{}, "app=synopsys-operator", false)
```
Comment (rrati) [inline pkg/synopsysctl/cmd_destroy.go]: Deleting the NS will delete all resources in the NS, so this should only be done in NS mode I think?  Should be in an else block I think.

File: pkg/synopsysctl/cmd_destroy.go [hunk 18]
```diff
@@ -153,18 +166,8 @@ func destroy(namespace string) error {
...
-		err = util.DeleteRoleBinding(kubeClient, namespace, roleBinding)
-
-		if err != nil {
-			log.Errorf("unable to delete role binding '%s' due to %+v", roleBinding, err)
-		}
-	}
-
 	// delete cluster roles
-	clusterRoles, roles, err := util.GetOperatorRoles(kubeClient, namespace)
+	clusterRoles, _, err := util.GetOperatorRoles(kubeClient, namespace)
```
Comment (rrati) [inline pkg/synopsysctl/cmd_destroy.go]: Delete cluster roles before role bindings.  You are using CRB in the RB delete logic, so want to use untouched CRB.

File: pkg/synopsysctl/utils.go [hunk 19]
```diff
@@ -236,12 +236,13 @@ func getInstanceInfo(mock bool, name string, crdType string, crdName string, inp
 
 	// Check Number of Arguments
 	if crdScope != apiextensions.ClusterScoped && len(namespace) == 0 {
-		return "", "", "", fmt.Errorf("namespace to create an '%s' instance needs to be provided", inputNamespace)
+		return "", "", "", fmt.Errorf("namespace needs to be provided. please use 'namespace' option to set them")
```
Comment (rrati) [inline pkg/synopsysctl/utils.go]: please use the 'namespace' to set it

File: pkg/synopsysctl/cmd_destroy.go (hunk 1 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: done

File: pkg/synopsysctl/cmd_destroy.go (hunk 18 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: as per the discussion, ignoring

File: pkg/synopsysctl/cmd_destroy.go (hunk 16 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: done

File: pkg/synopsysctl/cmd_destroy.go (hunk 17 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: done

File: pkg/synopsysctl/cmd_destroy.go (hunk 15 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: done

File: pkg/synopsysctl/cmd_destroy.go (hunk 14 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: done

File: pkg/synopsysctl/cmd_destroy.go (hunk 4 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_destroy.go]: done

File: pkg/synopsysctl/utils.go (hunk 19 above)
Comment (msenmurugan) [reply pkg/synopsysctl/utils.go]: done

**Comment by operator-r2d2** [comment]
@msenmurugan: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/559#" title="Author self-approved">msenmurugan</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/559#pullrequestreview-255233509" title="Approved">rrati</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [msenmurugan,rrati]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/559#" title="Author self-approved">msenmurugan</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/559#issuecomment-506357579" title="LGTM">rrati</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [msenmurugan,rrati]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by operator-r2d2** [comment]
@msenmurugan: new pull request created: #589

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/559#issuecomment-505724401):

>/cherrypick release-2019.6.x


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
