### PR TITLE
multiple volume fix

### LINKED ISSUE #630: External DB password is not set correctly in the secret
**What happened**:
The blackduck-db-creds secret contains the base64 password

**What you expected to happen**:
blackduck-db-creds secret need to contain the actual password

**How to reproduce it (as minimally and precisely as possible)**:
Create a Black Duck instance with external postgres

### PR DESCRIPTION
**Pull request by msenmurugan**
* multiple volume fix
  - support for migrate
  - zookeeper and upload cache changes
* external postgres password fix

fixes #630

### CODE REVIEW

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#" title="Author self-approved">msenmurugan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [msenmurugan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#issuecomment-509606602" title="Approved">jdartigalongue</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#" title="Author self-approved">msenmurugan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [jdartigalongue,msenmurugan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: pkg/synopsysctl/cmd_migrate.go [hunk 1]
```diff
@@ -324,24 +348,127 @@ func migrateBlackDuck(namespace string) error {
...
 }
 
-func removePVC(blackDuckNamespace string) error {
-	_, err := util.GetPVC(kubeClient, blackDuckNamespace, "blackduck-rabbitmq")
+// removePVC removes the PVC
+func removePVC(namespace string, name string, rabbitmqRCName string) error {
+	_, err := util.GetPVC(kubeClient, namespace, name)
 	if err == nil {
-		return util.DeletePVC(kubeClient, blackDuckNamespace, "blackduck-rabbitmq")
+		if "blackduck-rabbitmq" == name {
```
Comment (rrati) [inline pkg/synopsysctl/cmd_migrate.go]: Move this check and scale down of rabbitmq to outside the function.  removePVC should only be responsible for removing the PVC told to remove.

File: pkg/synopsysctl/cmd_migrate.go [hunk 2]
```diff
@@ -324,24 +348,127 @@ func migrateBlackDuck(namespace string) error {
...
+			Name: "migrate-upload-cache",
+		},
+		Spec: batchv1.JobSpec{
+			Template: corev1.PodTemplateSpec{
+				Spec: corev1.PodSpec{
+					Containers: []corev1.Container{
+						{
+							Name:    "migrate-key",
+							Image:   busyBoxImage,
+							Command: []string{"sh", "-c", "cp -pr /tmp/keys /opt/blackduck/hub/blackduck-upload-cache"},
```
Comment (rrati) [inline pkg/synopsysctl/cmd_migrate.go]: should we add -f option in case the migrate is re-run?  Job might fail on re-run otherwise.

File: pkg/synopsysctl/cmd_migrate.go [hunk 3]
```diff
@@ -324,24 +348,127 @@ func migrateBlackDuck(namespace string) error {
...
+			},
+		},
+	}
+
+	job, err := kubeClient.BatchV1().Jobs(namespace).Create(migrateJob)
+	if err != nil {
+		return err
+	}
+
+	timeout := time.After(30 * time.Minute)
```
Comment (rrati) [inline pkg/synopsysctl/cmd_migrate.go]: This seems like a really long timeout in the worst case situation.  If we handle re-run properly then this should be short imo.  No longer than 5 minutes imo.  @jdartigalongue thoughts?

File: pkg/synopsysctl/cmd_migrate.go [hunk 4]
```diff
@@ -324,24 +348,127 @@ func migrateBlackDuck(namespace string) error {
...
+	tick := time.Tick(10 * time.Second)
```
Comment (rrati) [inline pkg/synopsysctl/cmd_migrate.go]: Add defer close on the timeout and ticker to stop them once everything is complete.

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#issuecomment-509606602" title="Approved">jdartigalongue</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#" title="Author self-approved">msenmurugan</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#pullrequestreview-259657561" title="Approved">rrati</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [jdartigalongue,msenmurugan,rrati]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: pkg/synopsysctl/cmd_migrate.go (hunk 1 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_migrate.go]: done

File: pkg/synopsysctl/cmd_migrate.go (hunk 2 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_migrate.go]: done

File: pkg/synopsysctl/cmd_migrate.go (hunk 4 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_migrate.go]: done

File: pkg/synopsysctl/cmd_migrate.go [hunk 5]
```diff
@@ -324,22 +348,154 @@ func migrateBlackDuck(namespace string) error {
...
+			if value, ok := blackDuck.Annotations["synopsys.com/created.by"]; ok && "pre-2019.6.0" == value {
+				pvcs = append(pvcs, "zookeeper-data", "zookeeper-datalog")
+			} else {
+				pvcs = append(pvcs, util.GetResourceName(blackDuckName, util.BlackDuckName, "zookeeper-data"), util.GetResourceName(blackDuckName, util.BlackDuckName, "zookeeper-datalog"))
+			}
+			for _, pvc := range pvcs {
+				// check for an existance of PVC
+				_, err := util.GetPVC(kubeClient, blackDuckNamespace, pvc)
+				if err == nil {
+					if "blackduck-rabbitmq" == pvc {
```
Comment (rrati) [inline pkg/synopsysctl/cmd_migrate.go]: Scaling down and removing PVC are really separate actions.  Suggest:
for _, pvc := range pvcs{
  If "blackduck-rabbitmq" == pvc {
  ...
  }
  if err := removePVC(...); err != nil {
    return err
  }

And have removePVC do a get and delete if no error (like before this change)

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#issuecomment-509606602" title="Approved">jdartigalongue</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#" title="Author self-approved">msenmurugan</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#pullrequestreview-260195857" title="Approved">rrati</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [jdartigalongue,msenmurugan,rrati]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

File: pkg/synopsysctl/cmd_migrate.go [hunk 6]
```diff
@@ -324,22 +348,154 @@ func migrateBlackDuck(namespace string) error {
...
+			if err != nil {
+				return err
+			}
+			// scale down upload cache
+			err = scaleDownRC(blackDuckNamespace, uploadCacheRCName)
 			if err != nil {
 				return err
 			}
+
+			isSourceCodeEnabled := isSourceCodeEnabled(blackDuck.Spec.Environs)
```
[the remark this answers is not in the document]
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_migrate.go]: done

File: pkg/synopsysctl/cmd_migrate.go (hunk 5 above)
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_migrate.go]: @rrati correct but whenever there is PVC for rabbitmq (only for 2019.4.x operator case), then only scale down..

File: pkg/synopsysctl/cmd_migrate.go [hunk 7]
```diff
@@ -324,22 +348,154 @@ func migrateBlackDuck(namespace string) error {
...
 }
 
-func removePVC(blackDuckNamespace string) error {
-	_, err := util.GetPVC(kubeClient, blackDuckNamespace, "blackduck-rabbitmq")
+func isSourceCodeEnabled(environs []string) bool {
+	for _, value := range environs {
+		if strings.Contains(value, "ENABLE_SOURCE_UPLOADS") {
+			values := strings.SplitN(value, ":", 2)
+			if len(values) == 2 {
+				mapValue := strings.TrimSpace(values[1])
```
[the remark this answers is not in the document]
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_migrate.go]: @rrati  ENABLE_SOURCE_UPLOADS is the config map key.. we cannot change to lowercase

[the remark this answers is not in the document]
Comment (msenmurugan) [reply pkg/synopsysctl/cmd_migrate.go]: done

**Comment by operator-r2d2** [comment]
@rrati: once the present PR merges, I will cherry-pick it on top of release-2019.6.x in a new PR and assign it to you.

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/629#issuecomment-510142143):

>/cherrypick release-2019.6.x


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by operator-r2d2** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#issuecomment-509606602" title="Approved">jdartigalongue</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#" title="Author self-approved">msenmurugan</a>*, *<a href="https://github.com/blackducksoftware/synopsys-operator/pull/629#pullrequestreview-260227139" title="LGTM">rrati</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=blackducksoftware%2Fsynopsys-operator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/blackducksoftware/synopsys-operator/blob/master/OWNERS)~~ [jdartigalongue,msenmurugan,rrati]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by operator-r2d2** [comment]
@rrati: new pull request created: #642

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/pull/629#issuecomment-510142143):

>/cherrypick release-2019.6.x


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
